module:
    hugoVersion:
        extended: true
        min: "0.87.0"

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since:
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        compact: false
        emoji: 🥰
        subtitle: 一个天天都在想她的白痴
        avatar:
            enabled: true
            local: false
            src: https://s2.loli.net/2024/11/21/sStDMNkwvinG6ce.png

    article:
        headingAnchor: false
        math: true
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: giscus

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        beaudar:
            repo:
            issueTerm: pathname
            label:
            theme:        

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client/props.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - nick
                - mail
            locale:
                admin: Admin
                placeholder:

        twikoo:
            envId:
            region:
            path:
            lang:

        giscus:
            repo: DvdBr3o/blog-space
            repoID: R_kgDONYYyEw
            category: Announcements
            categoryID: DIC_kwDONYYyE84Ck4tK
            mapping: pathname
            strict: 0
            lightTheme: preferred_color_scheme
            darkTheme: preferred_color_scheme
            reactionsEnabled: 1
            emitMetadata: 0
            inputPosition: bottom
            lang: zh-CN

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        cusdis:
            host:
            id:

    widgets:
        homepage: 
            - type: search
            - type: tag-cloud
            - type: archives
        page:
            - type: search
            - type: tag-cloud
            - type: archives
            - type: toc

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: 首页
          url: /
          weight: -100
          params:
            icon: home
            newTab: false
        - identifier: categories
          name: 分类
          url: /categories
          weight: -80
          params:
            icon: categories
            newTab: false
